services:
  - type: web
    name: confession-app
    env: php
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan key:generate
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host=127.0.0.0 --port=8000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://confession-app.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: confession-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: confession-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: confession-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: confession-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: confession-db
          property: password

databases:
  - name: confession-db
    databaseName: confession_db
    user: confession_user
    plan: free
    engine: mysql 